# Site settings
title: Great New Blog Title
author:
  name: Thinh Vo
  email: vohongthinh2011@gmail.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
